CREATE TABLE IF NOT EXISTS `praticien` (
`PRA_NUM` int(11) NOT NULL AUTO_INCREMENT,
`PRA_NOM` varchar(100) NOT NULL,
`PRA_PRENOM` varchar(30) NOT NULL,
`PRA_ADRESSE` varchar(500) NOT NULL,
`PRA_CP` varchar(300) NOT NULL,
`PRA_VILLE` varchar(300) NOT NULL,
`PRA_COEFNOTORIETE` varchar(300) NOT NULL,
UNIQUE KEY `PRA_NUM` (`PRA_NUM`)
) ENGINE=innoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=10 ;

CREATE TABLE IF NOT EXISTS `specialite` (
`SPE_NUM` int(11) NOT NULL,
`SPE_LIBELLE` varchar(100) NOT NULL,
UNIQUE KEY `SPE_NUM` (`SPE_NUM`)
) ENGINE=innoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=10 ;